name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create reports directory
      run: mkdir -p reports
        
    - name: Lint with flake8
      continue-on-error: true
      run: |
        echo "=== Flake8 Linting Report ===" > reports/flake8_report.txt
        echo "Python files analyzed:" >> reports/flake8_report.txt
        find . -name "*.py" | grep -v "venv/" >> reports/flake8_report.txt
        echo "\nDetailed findings:" >> reports/flake8_report.txt
        flake8 . --count --statistics --show-source --max-line-length=100 --format="%(path)s:%(row)d:%(col)d: %(code)s %(text)s" >> reports/flake8_report.txt 2>&1 || true
        cat reports/flake8_report.txt
        
    - name: Static analysis with pylint
      continue-on-error: true
      run: |
        echo "=== Pylint Static Analysis Report ===" > reports/pylint_report.txt
        pylint --rcfile=setup.cfg $(git ls-files '*.py') --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" >> reports/pylint_report.txt 2>&1 || true
        cat reports/pylint_report.txt

    - name: Upload code quality reports
      uses: actions/upload-artifact@v3
      with:
        name: code-quality-reports
        path: reports/
        retention-days: 14

  build-and-test:
    needs: quality
    runs-on: ubuntu-latest
    services:
      api:
        image: temperature-api
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 5s
      
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Build Docker image
      run: docker build -t temperature-api .
      
    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov requests pandas numpy
        
    - name: Run all tests with retry
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 5
        max_attempts: 3
        command: |
          pytest tests/ \
            --cov=. \
            --cov-report=html:reports/coverage-html \
            --cov-report=xml:reports/coverage.xml \
            -v \
            --junitxml=reports/junit.xml
        
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: |
          reports/coverage-html/
          reports/coverage.xml
          reports/junit.xml
        retention-days: 14